// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0hqBmy9pQsUj2AFhczIezEwuWBwKAEKk',
    appId: '1:477104588795:web:be48d3cfd90e296cd5ad5e',
    messagingSenderId: '477104588795',
    projectId: 'dhc-assignment',
    authDomain: 'dhc-assignment.firebaseapp.com',
    storageBucket: 'dhc-assignment.firebasestorage.app',
    measurementId: 'G-5W242P8MTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdgv0eHAKUJR1CgidaXG61jCkYmaoX1Sk',
    appId: '1:477104588795:android:6bf095c2f7d85696d5ad5e',
    messagingSenderId: '477104588795',
    projectId: 'dhc-assignment',
    storageBucket: 'dhc-assignment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt9X6G96DXJV6CBp7bDlx9Z7vmXDa_Ytc',
    appId: '1:477104588795:ios:bce7c8f18be7e9edd5ad5e',
    messagingSenderId: '477104588795',
    projectId: 'dhc-assignment',
    storageBucket: 'dhc-assignment.firebasestorage.app',
    iosBundleId: 'com.example.dhcAssignment',
  );
}
